import type { Config } from 'tailwindcss'

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'on-surface': 'var(--color-on-surface)',
        'surface-container': 'var(--color-surface-container)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'surface-bright': 'var(--color-surface-bright)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'error-container': 'var(--color-error-container)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'surface-variant': 'var(--color-surface-variant)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'surface-dim': 'var(--color-surface-dim)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'background': 'var(--color-background)',
        'tertiary': 'var(--color-tertiary)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'on-secondary': 'var(--color-on-secondary)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'outline-variant': 'var(--color-outline-variant)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'error': 'var(--color-error)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'on-primary': 'var(--color-on-primary)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-background': 'var(--color-on-background)',
        'surface': 'var(--color-surface)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'primary': 'var(--color-primary)',
        'outline': 'var(--color-outline)',
        'on-error-container': 'var(--color-on-error-container)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'primary-container': 'var(--color-primary-container)',
        'secondary': 'var(--color-secondary)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'surface-tint': 'var(--color-surface-tint)',
        'on-error': 'var(--color-on-error)',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
      spacing: {
        'sm': '16px',
        'lg': '48px',
        'gutter': '24px',
        'container-max': '1280px',
        'md': '24px',
        'xs': '8px',
        'base': '4px',
        'xl': '80px',
      },
      fontFamily: {
        'display-lg-mobile': ['Space Grotesk'],
        'headline-md': ['Space Grotesk'],
        'label-sm': ['DM Sans'],
        'body-lg': ['DM Sans'],
        'display-lg': ['Space Grotesk'],
        'body-md': ['DM Sans'],
        'display-xl': ['Space Grotesk'],
        'label-md': ['DM Sans'],
        'headline-lg': ['Space Grotesk'],
      },
      fontSize: {
        'display-lg-mobile': ['36px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
} satisfies Config
